import type { Program, Campus } from '@/lib/types';

export const campuses: Campus[] = [
  { id: 'casa-sidi-maarouf', name: 'ISTA Sidi Maârouf', city: 'Casablanca', address: 'Quartier des Affaires, Sidi Maârouf', phone: '+212 522 00 00 00', url: 'https://ofppt.ma/casa-sidi-maarouf' },
  { id: 'rabat-hay-riad', name: 'ISTA Hay Riad', city: 'Rabat', address: 'Avenue Annakhil, Hay Riad', phone: '+212 537 00 00 00', url: 'https://ofppt.ma/rabat-hay-riad' },
  { id: 'tanger-technopole', name: 'Cité des Métiers et des Compétences', city: 'Tanger', address: 'Technopole de Tanger', phone: '+212 539 00 00 00', url: 'https://ofppt.ma/tanger-cmc' },
  { id: 'marrakech-el-azzouzia', name: 'ISTA El Azzouzia', city: 'Marrakech', address: 'Zone Industrielle El Azzouzia', phone: '+212 524 00 00 00', url: 'https://ofppt.ma/marrakech-el-azzouzia' },
];

export const programs: Program[] = [
  {
    id: 'dev-fullstack-ts',
    title: 'Développement Full Stack',
    level: 'Technicien Spécialisé',
    domain: 'Développement',
    durationMonths: 24,
    campuses: ['casa-sidi-maarouf', 'rabat-hay-riad'],
    prerequisites: ['Baccalauréat (toutes séries)'],
    description: 'Ce programme forme des développeurs polyvalents capables de créer des applications web complètes, du back-end au front-end, en utilisant les technologies les plus récentes.',
    officialUrl: 'https://ofppt.ma/programs/dev-fullstack',
    updatedAt: '2024-05-20T10:00:00Z',
    imageId: 'dev',
    modules: ['Algorithmique', 'Bases de données SQL & NoSQL', 'Développement Back-end (Node.js, Express)', 'Développement Front-end (React, Angular)', 'Déploiement & DevOps'],
    outcomes: ['Maîtrise des stacks MERN/MEAN', 'Conception d\'API RESTful', 'Développement d\'interfaces utilisateur réactives'],
    certifications: ['Certification interne OFPPT', 'Préparation à la certification AWS Cloud Practitioner'],
    admission: 'Admission sur dossier et entretien.',
    schedule: 'Cours du jour, du lundi au vendredi.',
    tuition: 'Frais de scolarité annuels de 950 DH.'
  },
  {
    id: 'data-analyst-ts',
    title: 'Analyse de Données & IA',
    level: 'Technicien Spécialisé',
    domain: 'Données',
    durationMonths: 24,
    campuses: ['casa-sidi-maarouf', 'tanger-technopole'],
    prerequisites: ['Baccalauréat Scientifique ou Technique'],
    description: 'Apprenez à collecter, traiter et visualiser des données pour en extraire des informations stratégiques et à développer des modèles d\'intelligence artificielle.',
    officialUrl: 'https://ofppt.ma/programs/data-analyst',
    updatedAt: '2024-05-18T14:30:00Z',
    imageId: 'data',
    modules: ['Statistiques appliquées', 'Python pour la Data Science', 'Machine Learning', 'Data Visualization (Tableau, Power BI)', 'Big Data Technologies'],
    outcomes: ['Création de dashboards interactifs', 'Développement de modèles prédictifs', 'Manipulation de grands volumes de données'],
    certifications: ['Certification interne OFPPT', 'Certification Microsoft Power BI Data Analyst Associate'],
    admission: 'Admission sur dossier et test de logique.',
    schedule: 'Cours du jour, du lundi au vendredi.',
    tuition: 'Frais de scolarité annuels de 950 DH.'
  },
  {
    id: 'reseaux-cloud-t',
    title: 'Réseaux & Cloud Computing',
    level: 'Technicien',
    domain: 'Réseaux',
    durationMonths: 24,
    campuses: ['rabat-hay-riad', 'marrakech-el-azzouzia'],
    prerequisites: ['Niveau Baccalauréat'],
    description: 'Ce cursus couvre l\'administration des réseaux informatiques et les fondamentaux des services cloud, préparant aux métiers de technicien réseau et d\'administrateur cloud junior.',
    officialUrl: 'https://ofppt.ma/programs/reseaux-cloud',
    updatedAt: '2024-05-21T09:00:00Z',
    imageId: 'network',
    modules: ['Architecture réseau (TCP/IP)', 'Administration Windows Server & Linux', 'Virtualisation', 'Services Cloud (AWS, Azure)', 'Sécurité des réseaux'],
    outcomes: ['Configuration de routeurs et switchs', 'Gestion d\'infrastructures virtualisées', 'Déploiement de services sur le cloud'],
    certifications: ['Certification interne OFPPT', 'Préparation à la certification Cisco CCNA'],
    admission: 'Admission sur dossier.',
    schedule: 'Cours du jour et cours du soir disponibles.',
    tuition: 'Frais de scolarité annuels de 750 DH.'
  },
  {
    id: 'cybersecurity-ts',
    title: 'Cybersécurité',
    level: 'Technicien Spécialisé',
    domain: 'Cybersecurity',
    durationMonths: 24,
    campuses: ['tanger-technopole'],
    prerequisites: ['Baccalauréat Scientifique ou Technique'],
    description: 'Devenez un expert en protection des systèmes d\'information. Ce programme aborde les techniques de défense, la détection des menaces et la réponse aux incidents.',
    officialUrl: 'https://ofppt.ma/programs/cybersecurity',
    updatedAt: '2024-05-22T11:00:00Z',
    imageId: 'cyber',
    modules: ['Cryptographie', 'Sécurité des applications web', 'Audit de sécurité & tests d\'intrusion', 'Gestion des identités et des accès (IAM)', 'Forensics numérique'],
    outcomes: ['Analyse de malwares', 'Configuration de pare-feux et de systèmes de détection d\'intrusion', 'Mise en place de politiques de sécurité'],
    certifications: ['Certification interne OFPPT', 'Préparation à la certification CompTIA Security+'],
    admission: 'Admission sur dossier, test technique et entretien.',
    schedule: 'Cours du jour, du lundi au vendredi.',
    tuition: 'Frais de scolarité annuels de 950 DH.'
  },
   {
    id: 'devops-cloud-ts',
    title: 'Cloud & DevOps',
    level: 'Technicien Spécialisé',
    domain: 'Cloud',
    durationMonths: 24,
    campuses: ['casa-sidi-maarouf', 'rabat-hay-riad'],
    prerequisites: ['Baccalauréat Technique ou Diplôme de Technicien en Informatique'],
    description: 'Ce programme est axé sur l\'automatisation des processus de développement et de déploiement d\'applications sur des infrastructures cloud modernes.',
    officialUrl: 'https://ofppt.ma/programs/devops-cloud',
    updatedAt: '2024-05-19T16:00:00Z',
    imageId: 'cloud',
    modules: ['Infrastructure as Code (Terraform)', 'Intégration et Déploiement Continus (CI/CD) avec Jenkins/GitLab CI', 'Conteneurisation (Docker, Kubernetes)', 'Monitoring & Logging (Prometheus, ELK)', 'Architecture Cloud Native'],
    outcomes: ['Automatisation du cycle de vie logiciel', 'Orchestration de conteneurs à grande échelle', 'Gestion d\'infrastructures cloud résilientes'],
    certifications: ['Certification interne OFPPT', 'Préparation à la certification "HashiCorp Certified: Terraform Associate"'],
    admission: 'Admission sur dossier et entretien technique.',
    schedule: 'Cours du jour, du lundi au vendredi.',
    tuition: 'Frais de scolarité annuels de 950 DH.'
  }
];
